import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

// The sheet is a decision artifact. It is generated from the generator so a
// candidate on the page cannot differ from what shipping that candidate would
// draw, which is the same reason scripts/build_dot_pages.py exists.
describe('the micro contact sheet', () => {
  it('is generated by the generator, not hand-written', () => {
    execFileSync('python', ['scripts/render_mark.py', '--sheet'], { encoding: 'utf8' });
    expect(existsSync('prototypes/marks-micro.html')).toBe(true);
  });

  it('shows every candidate in both polarities at true size', () => {
    const html = readFileSync('prototypes/marks-micro.html', 'utf8');
    // twelve candidates, each drawn ink-on-light and light-on-ink. Count
    // distinct ids, not occurrences: each polarity is emitted four times, at
    // 16, 19 and 20px plus the zoom.
    const ids = new Set([...html.matchAll(/data-candidate="([^"]+)"/g)].map((m) => m[1]));
    expect(ids.size).toBe(24);
    // true 16, 19 and 20px, plus a 6x zoom, per polarity
    expect(html).toContain('width:16px');
    expect(html).toContain('width:19px');
    expect(html).toContain('width:20px');
    expect(html).toContain('width:96px');
  });

  it('prints the measurable criteria beside each candidate so the choice is informed', () => {
    const html = readFileSync('prototypes/marks-micro.html', 'utf8');
    for (const label of ['dots', 'densest', 'coverage', 'legible at 16']) {
      expect(html).toContain(label);
    }
  });

  it('does not touch the shipped assets', () => {
    const before = readFileSync('public/assets/mark/mark.svg', 'utf8');
    execFileSync('python', ['scripts/render_mark.py', '--sheet'], { encoding: 'utf8' });
    expect(readFileSync('public/assets/mark/mark.svg', 'utf8')).toBe(before);
  });
});
